/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1
 */
public class PazireshDialoge_Release extends javax.swing.JFrame {

    /**
     * Creates new form PazireshDialoge_Release
     */

    public PazireshDialoge_Release() throws FileNotFoundException {
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(2);
        
        read();
    }
    void read() throws FileNotFoundException
    {
        this.hospital=HospitalReader.read_Hospital();
        java.util.ArrayList<String> sa=new java.util.ArrayList<>();
        for(int i=0;i<hospital.get_Sicks().size();i++)
        {
            sa.add(hospital.get_Sicks().get(i).to_String2()+"    نوع اتاق:"+hospital.Floors.get(hospital.get_Sicks().get(i).Room_id/100).Rooms.get(hospital.get_Sicks().get(i).Room_id%100).Room_Type.toString());
        }
        this.jList1.setListData(sa.toArray());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("نام");

        jLabel2.setText("نام خانوادگی");

        jButton1.setText("جستجو");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("ترخیص بیمار");

        jButton2.setText("ترخیص");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(349, 349, 349))))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(309, 309, 309)))
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Hospital hospital;
    Sick sick=null;
    void search_by_Name_And_Family(String name,String family,javax.swing.JList list_to_write)
    {
        java.util.ArrayList<String> ar=new java.util.ArrayList<>();
        for(int i=0;i<hospital.get_Sicks().size();i++)
        {
            if(hospital.get_Sicks().get(i).get_Name().contains(name)&&hospital.get_Sicks().get(i).get_Family().contains(family))
            {
                ar.add(hospital.get_Sicks().get(i).to_String2()+"    نوع اتاق:"+hospital.Floors.get(hospital.get_Sicks().get(i).Room_id/100).Rooms.get(hospital.get_Sicks().get(i).Room_id%100).Room_Type.toString());
            }
        }
        list_to_write.setListData(ar.toArray());
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.search_by_Name_And_Family(this.jTextField1.getText(),this.jTextField2.getText(),this.jList1);
        /*int stt=0;
        
        for(int i=0;i<hospital.get_Sicks().size();i++)
        {
        if(hospital.get_Sicks().get(i).Room_id==Integer.parseInt(this.jTextField1.getText())&&hospital.get_Sicks().get(i).Bed_id==Integer.parseInt(this.jTextField2.getText()))
        {
        stt=1;
        sick=hospital.get_Sicks().get(i);
        }
        
        }
        if(stt==0)
        {
        javax.swing.JOptionPane.showMessageDialog(rootPane,"بیمار مورد نظر یافت نشد");
        }
        else
        {
        String s="",s2="";
        if(sick.get_Gender().equals(Gender.Male))
        {
        s="آقا";
        }
        else
        {
        s="خانم";
        }
        if(hospital.Floors.get(sick.Room_id/100).Rooms.get(sick.Room_id%100).get_Room_Type().equals(RoomType.Emergency))
        {
        s2="اورژانس";
        }
        else if(hospital.Floors.get(sick.Room_id/100).Rooms.get(sick.Room_id%100).get_Room_Type().equals(RoomType.ICU))
        {
        s2="ICU";
        }
        else
        {
        s2="استریلیزه(1بیمار)";
        }
        this.jLabel3.setText("نام بیمار :"+sick.get_Name()+"  "+"نام خانوادگی بیمار"+sick.get_Family()+"  "+"\nجنسیت بیمار :"+s+"  "+"\n تاریخ تولد:"+sick.get_Birth_Date().show()+"  "+"\nتاریخ ورود :"+sick.Enter_Date.show()+"  "+"\nشماره اتاق :"+sick.get_Room_id()+"  "+"\nشماره تخت :"+sick.get_Bed_id()+"  "+"\nنوع بیماری :"+s2);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            if(this.jList1.getSelectedValue()!=null)
            {
            String ssa01=this.jList1.getSelectedValue().toString().split("    نوع اتاق:")[0];
            int bi=Integer.parseInt(ssa01.split("    شماره تخت:")[1]);
            String ssa=this.jList1.getSelectedValue().toString().split("    شماره تخت:")[0];
            int ri=Integer.parseInt(ssa.split("    شماره اتاق:")[1]);
            if(hospital.Floors.get(ri/100).Rooms.get(ri%100).Beds.get(bi).Has_Sick==true)
            {
                
                try 
                {
                    hospital.Floors.get(ri/100).Rooms.get(ri%100).Beds.get(bi).Release_Sick();
                    HospitalWriter.WriteHospital(hospital);
                    javax.swing.JOptionPane.showMessageDialog(rootPane,"بیمار ترخیص شد.");
                    this.dispose();
                }   
                catch (FileNotFoundException ex) 
                {
                    Logger.getLogger(PazireshDialoge_Release.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PazireshDialoge_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PazireshDialoge_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PazireshDialoge_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PazireshDialoge_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PazireshDialoge_Release().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(PazireshDialoge_Release.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
